---
- name: install updates (CentOS) 
  tags: always
  dnf:
    update_only: yes
    update_cache: yes
    use_backend: dnf4
  when: ansible distribution == "CentOS"

- name: install updates (Ubuntu)
  tags: always
  apt:
    upgrade: dist
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
