---
- name: install updates (CentOS) 
  tags: always
  yum:
    name: "*"
    update_only: yes
    update_cache: yes
  when: ansible distribution == "CentOS"

- name: install updates (Ubuntu)
  tags: always
  apt:
    upgrade: dist
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
