---
- name: Update package cache
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Update package cache
  yum:
    update_cache: yes
    name: '*'
    state: latest
  when: ansible_distribution == "CentOS"
